# Generated by Django 4.2.2 on 2023-08-30 10:39

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OfflineCashIssuance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("service_agreement_id", models.CharField(max_length=256)),
                ("previous_tx_hash", models.CharField(max_length=256)),
                ("amount", models.CharField(max_length=128)),
                ("from_did", models.CharField(max_length=256)),
                ("to_did", models.CharField(max_length=256)),
                ("issued_at", models.BigIntegerField()),
                ("expiry_at", models.BigIntegerField()),
                ("tx_hash", models.CharField(max_length=256)),
                ("signed_tx_hash", models.CharField(max_length=256)),
                ("has_claimed", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "offline_cash_issuance",
            },
        ),
        migrations.CreateModel(
            name="OfflineCashReq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("did", models.CharField(max_length=256)),
                ("bank_did", models.CharField(max_length=256)),
                ("amount", models.CharField(max_length=128)),
                (
                    "service_agreement_id",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("status", models.CharField(max_length=128)),
                ("signature", models.CharField(max_length=256)),
                ("hash", models.CharField(max_length=256)),
            ],
            options={
                "db_table": "offline_cash_req",
            },
        ),
        migrations.CreateModel(
            name="OfflineClaims",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("did", models.CharField(max_length=128)),
                ("amount", models.IntegerField()),
                ("status", models.CharField(max_length=128)),
                (
                    "offline_cash_cert_chain",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(max_length=1024), size=None
                    ),
                ),
                (
                    "cash_issuance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="offline_cash.offlinecashissuance",
                    ),
                ),
            ],
            options={
                "db_table": "offline_claims",
            },
        ),
    ]
