# Generated by Django 4.2.2 on 2023-09-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offline_cash", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterBankClearance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("from_bank", models.CharField(max_length=256)),
                ("to_bank", models.CharField(max_length=256)),
                ("amount", models.CharField(max_length=256)),
                ("claimed", models.BooleanField()),
            ],
            options={
                "db_table": "interbank_cash_clearance",
            },
        ),
    ]
