# Generated by Django 4.2.2 on 2023-10-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offline_cash", "0002_interbankclearance"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfflineCashQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("from_did", models.CharField(max_length=256)),
                ("to_did", models.CharField(max_length=256)),
                ("certificates", models.JSONField()),
                ("transactions", models.JSONField()),
                ("tx_hash", models.CharField(max_length=256)),
                ("signed_tx_hash", models.CharField(max_length=256)),
            ],
            options={
                "db_table": "offline_cash_queue",
            },
        ),
    ]
