# Generated by Django 4.2.2 on 2023-11-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offline_cash", "0004_cashsync"),
    ]

    operations = [
        migrations.AddField(
            model_name="offlinecashqueue",
            name="status",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
