# Generated by Django 4.2.2 on 2023-11-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offline_cash", "0006_cashissuancequeue"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashsync",
            name="transaction_type",
            field=models.CharField(default="PAYMENT", max_length=256),
            preserve_default=False,
        ),
    ]
