# Generated by Django 4.2.2 on 2024-01-12 19:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("offline_cash", "0007_cashsync_transaction_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CashIssuanceQueue",
        ),
        migrations.DeleteModel(
            name="CashSync",
        ),
        migrations.DeleteModel(
            name="InterBankClearance",
        ),
        migrations.DeleteModel(
            name="OfflineCashReq",
        ),
        migrations.RemoveField(
            model_name="offlineclaims",
            name="cash_issuance",
        ),
        migrations.DeleteModel(
            name="OfflineCashIssuance",
        ),
        migrations.DeleteModel(
            name="OfflineClaims",
        ),
    ]
